volumes:
  tsa:
    external: true
services:
  fastapi:
    environment:
      SIGNING_KEY: f2e06ef93a89cc71baba7f64144cea78ef8f85e128dab73acd4f1ed707793b10
      CORS_HOST: http://localhost:3000
      DATABASE_URL: postgresql://tsa:tsa@db/tsa
      WAIT_HOSTS: db:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      PORT: 8000
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
  db:
    image: postgres:14.5-bullseye
    volumes:
      - tsa:/var/lib/postgresql/db
    environment:
      POSTGRES_PASSWORD: tsa
      POSTGRES_USER: tsa
      POSTGRES_DB: tsa
    ports:
      - "15432:5432"
