volumes:
  tsa:
    external: true
services:
  fastapi:
    environment:
      SIGNING_KEY: ${SIGNING_KEY}
      CORS_HOST: ${CORS_HOST}
      DATABASE_URL: postgresql://tsa:tsa@db/tsa
      WAIT_HOSTS: db:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      PORT: 8000
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      SIGNING_KEY: ${SIGNING_KEY}
      HOST_OS: ${OS}
      NODE_ENV: ${NODE_ENV}
      HOST: ${HOST}
      PUBLIC_URL: ${PUBLIC_URL}
      VITE_REACT_APP_API_HOST: ${VITE_REACT_APP_API_HOST}
      VITE_REACT_APP_TRIP_ADVISOR_API_KEY: ${VITE_REACT_APP_TRIP_ADVISOR_API_KEY}
      VITE_REACT_APP_GOOGLE_MAPS_API_KEY: ${VITE_REACT_APP_GOOGLE_MAPS_API_KEY}
      VITE_TRIP_ADVISOR_API_URL: ${VITE_TRIP_ADVISOR_API_URL}
  db:
    image: postgres:14.5-bullseye
    volumes:
      - tsa:/var/lib/postgresql/db
    environment:
      SIGNING_KEY: ${SIGNING_KEY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "15432:5432"
